// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: game.proto

package protocolpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageId int32

const (
	MessageId_MESSAGE_ID_UNSPECIFIED              MessageId = 0
	MessageId_MESSAGE_ID_LOGIN_REQ                MessageId = 1001
	MessageId_MESSAGE_ID_LOGIN_RESP               MessageId = 1002
	MessageId_MESSAGE_ID_HEARTBEAT_REQ            MessageId = 1003
	MessageId_MESSAGE_ID_HEARTBEAT_RESP           MessageId = 1004
	MessageId_MESSAGE_ID_SAVE_ARCHIVE_REQ         MessageId = 2001
	MessageId_MESSAGE_ID_SAVE_ARCHIVE_RESP        MessageId = 2002
	MessageId_MESSAGE_ID_LOAD_ARCHIVE_REQ         MessageId = 2003
	MessageId_MESSAGE_ID_LOAD_ARCHIVE_RESP        MessageId = 2004
	MessageId_MESSAGE_ID_GET_RANK_REQ             MessageId = 3001
	MessageId_MESSAGE_ID_GET_RANK_RESP            MessageId = 3002
	MessageId_MESSAGE_ID_SUBMIT_SCORE_REQ         MessageId = 3003
	MessageId_MESSAGE_ID_SUBMIT_SCORE_RESP        MessageId = 3004
	MessageId_MESSAGE_ID_COMBAT_RESULT_REQ        MessageId = 4001
	MessageId_MESSAGE_ID_COMBAT_RESULT_RESP       MessageId = 4002
	MessageId_MESSAGE_ID_GET_ENEMY_CONFIGS_REQ    MessageId = 4003
	MessageId_MESSAGE_ID_GET_ENEMY_CONFIGS_RESP   MessageId = 4004
	MessageId_MESSAGE_ID_GET_DUNGEON_CONFIG_REQ   MessageId = 4005
	MessageId_MESSAGE_ID_GET_DUNGEON_CONFIG_RESP  MessageId = 4006
	MessageId_MESSAGE_ID_GET_STYLE_CONFIGS_REQ    MessageId = 4007
	MessageId_MESSAGE_ID_GET_STYLE_CONFIGS_RESP   MessageId = 4008
	MessageId_MESSAGE_ID_UNLOCK_STYLE_REQ         MessageId = 4009
	MessageId_MESSAGE_ID_UNLOCK_STYLE_RESP        MessageId = 4010
	MessageId_MESSAGE_ID_GET_PLAYER_STATS_REQ     MessageId = 4011
	MessageId_MESSAGE_ID_GET_PLAYER_STATS_RESP    MessageId = 4012
	MessageId_MESSAGE_ID_UPDATE_PLAYER_STATS_REQ  MessageId = 4013
	MessageId_MESSAGE_ID_UPDATE_PLAYER_STATS_RESP MessageId = 4014
	MessageId_MESSAGE_ID_CREATE_ORDER_REQ         MessageId = 5001
	MessageId_MESSAGE_ID_CREATE_ORDER_RESP        MessageId = 5002
	MessageId_MESSAGE_ID_PAY_RESULT_NOTIFY        MessageId = 5003
	MessageId_MESSAGE_ID_GM_COMMAND_REQ           MessageId = 6001
	MessageId_MESSAGE_ID_GM_COMMAND_RESP          MessageId = 6002
	MessageId_MESSAGE_ID_ERROR                    MessageId = 9999
)

// Enum value maps for MessageId.
var (
	MessageId_name = map[int32]string{
		0:    "MESSAGE_ID_UNSPECIFIED",
		1001: "MESSAGE_ID_LOGIN_REQ",
		1002: "MESSAGE_ID_LOGIN_RESP",
		1003: "MESSAGE_ID_HEARTBEAT_REQ",
		1004: "MESSAGE_ID_HEARTBEAT_RESP",
		2001: "MESSAGE_ID_SAVE_ARCHIVE_REQ",
		2002: "MESSAGE_ID_SAVE_ARCHIVE_RESP",
		2003: "MESSAGE_ID_LOAD_ARCHIVE_REQ",
		2004: "MESSAGE_ID_LOAD_ARCHIVE_RESP",
		3001: "MESSAGE_ID_GET_RANK_REQ",
		3002: "MESSAGE_ID_GET_RANK_RESP",
		3003: "MESSAGE_ID_SUBMIT_SCORE_REQ",
		3004: "MESSAGE_ID_SUBMIT_SCORE_RESP",
		4001: "MESSAGE_ID_COMBAT_RESULT_REQ",
		4002: "MESSAGE_ID_COMBAT_RESULT_RESP",
		4003: "MESSAGE_ID_GET_ENEMY_CONFIGS_REQ",
		4004: "MESSAGE_ID_GET_ENEMY_CONFIGS_RESP",
		4005: "MESSAGE_ID_GET_DUNGEON_CONFIG_REQ",
		4006: "MESSAGE_ID_GET_DUNGEON_CONFIG_RESP",
		4007: "MESSAGE_ID_GET_STYLE_CONFIGS_REQ",
		4008: "MESSAGE_ID_GET_STYLE_CONFIGS_RESP",
		4009: "MESSAGE_ID_UNLOCK_STYLE_REQ",
		4010: "MESSAGE_ID_UNLOCK_STYLE_RESP",
		4011: "MESSAGE_ID_GET_PLAYER_STATS_REQ",
		4012: "MESSAGE_ID_GET_PLAYER_STATS_RESP",
		4013: "MESSAGE_ID_UPDATE_PLAYER_STATS_REQ",
		4014: "MESSAGE_ID_UPDATE_PLAYER_STATS_RESP",
		5001: "MESSAGE_ID_CREATE_ORDER_REQ",
		5002: "MESSAGE_ID_CREATE_ORDER_RESP",
		5003: "MESSAGE_ID_PAY_RESULT_NOTIFY",
		6001: "MESSAGE_ID_GM_COMMAND_REQ",
		6002: "MESSAGE_ID_GM_COMMAND_RESP",
		9999: "MESSAGE_ID_ERROR",
	}
	MessageId_value = map[string]int32{
		"MESSAGE_ID_UNSPECIFIED":              0,
		"MESSAGE_ID_LOGIN_REQ":                1001,
		"MESSAGE_ID_LOGIN_RESP":               1002,
		"MESSAGE_ID_HEARTBEAT_REQ":            1003,
		"MESSAGE_ID_HEARTBEAT_RESP":           1004,
		"MESSAGE_ID_SAVE_ARCHIVE_REQ":         2001,
		"MESSAGE_ID_SAVE_ARCHIVE_RESP":        2002,
		"MESSAGE_ID_LOAD_ARCHIVE_REQ":         2003,
		"MESSAGE_ID_LOAD_ARCHIVE_RESP":        2004,
		"MESSAGE_ID_GET_RANK_REQ":             3001,
		"MESSAGE_ID_GET_RANK_RESP":            3002,
		"MESSAGE_ID_SUBMIT_SCORE_REQ":         3003,
		"MESSAGE_ID_SUBMIT_SCORE_RESP":        3004,
		"MESSAGE_ID_COMBAT_RESULT_REQ":        4001,
		"MESSAGE_ID_COMBAT_RESULT_RESP":       4002,
		"MESSAGE_ID_GET_ENEMY_CONFIGS_REQ":    4003,
		"MESSAGE_ID_GET_ENEMY_CONFIGS_RESP":   4004,
		"MESSAGE_ID_GET_DUNGEON_CONFIG_REQ":   4005,
		"MESSAGE_ID_GET_DUNGEON_CONFIG_RESP":  4006,
		"MESSAGE_ID_GET_STYLE_CONFIGS_REQ":    4007,
		"MESSAGE_ID_GET_STYLE_CONFIGS_RESP":   4008,
		"MESSAGE_ID_UNLOCK_STYLE_REQ":         4009,
		"MESSAGE_ID_UNLOCK_STYLE_RESP":        4010,
		"MESSAGE_ID_GET_PLAYER_STATS_REQ":     4011,
		"MESSAGE_ID_GET_PLAYER_STATS_RESP":    4012,
		"MESSAGE_ID_UPDATE_PLAYER_STATS_REQ":  4013,
		"MESSAGE_ID_UPDATE_PLAYER_STATS_RESP": 4014,
		"MESSAGE_ID_CREATE_ORDER_REQ":         5001,
		"MESSAGE_ID_CREATE_ORDER_RESP":        5002,
		"MESSAGE_ID_PAY_RESULT_NOTIFY":        5003,
		"MESSAGE_ID_GM_COMMAND_REQ":           6001,
		"MESSAGE_ID_GM_COMMAND_RESP":          6002,
		"MESSAGE_ID_ERROR":                    9999,
	}
)

func (x MessageId) Enum() *MessageId {
	p := new(MessageId)
	*p = x
	return p
}

func (x MessageId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageId) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[0].Descriptor()
}

func (MessageId) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[0]
}

func (x MessageId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageId.Descriptor instead.
func (MessageId) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

type BattleOutcome int32

const (
	BattleOutcome_BATTLE_OUTCOME_UNSPECIFIED BattleOutcome = 0
	BattleOutcome_BATTLE_OUTCOME_VICTORY     BattleOutcome = 1
	BattleOutcome_BATTLE_OUTCOME_DEFEAT      BattleOutcome = 2
)

// Enum value maps for BattleOutcome.
var (
	BattleOutcome_name = map[int32]string{
		0: "BATTLE_OUTCOME_UNSPECIFIED",
		1: "BATTLE_OUTCOME_VICTORY",
		2: "BATTLE_OUTCOME_DEFEAT",
	}
	BattleOutcome_value = map[string]int32{
		"BATTLE_OUTCOME_UNSPECIFIED": 0,
		"BATTLE_OUTCOME_VICTORY":     1,
		"BATTLE_OUTCOME_DEFEAT":      2,
	}
)

func (x BattleOutcome) Enum() *BattleOutcome {
	p := new(BattleOutcome)
	*p = x
	return p
}

func (x BattleOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BattleOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[1].Descriptor()
}

func (BattleOutcome) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[1]
}

func (x BattleOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BattleOutcome.Descriptor instead.
func (BattleOutcome) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *LoginReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type LoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResp) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *LoginResp) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *LoginResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type HeartbeatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatReq) Reset() {
	*x = HeartbeatReq{}
	mi := &file_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatReq) ProtoMessage() {}

func (x *HeartbeatReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatReq.ProtoReflect.Descriptor instead.
func (*HeartbeatReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatReq) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type HeartbeatResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResp) Reset() {
	*x = HeartbeatResp{}
	mi := &file_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResp) ProtoMessage() {}

func (x *HeartbeatResp) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResp.ProtoReflect.Descriptor instead.
func (*HeartbeatResp) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResp) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type PlayerArchive struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion         int32                  `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Gold                  int32                  `protobuf:"varint,2,opt,name=gold,proto3" json:"gold,omitempty"`
	Exp                   int32                  `protobuf:"varint,3,opt,name=exp,proto3" json:"exp,omitempty"`
	BestScore             int64                  `protobuf:"varint,4,opt,name=best_score,json=bestScore,proto3" json:"best_score,omitempty"`
	TotalKills            int64                  `protobuf:"varint,5,opt,name=total_kills,json=totalKills,proto3" json:"total_kills,omitempty"`
	TotalGames            int64                  `protobuf:"varint,6,opt,name=total_games,json=totalGames,proto3" json:"total_games,omitempty"`
	HighestClearedDungeon int32                  `protobuf:"varint,7,opt,name=highest_cleared_dungeon,json=highestClearedDungeon,proto3" json:"highest_cleared_dungeon,omitempty"`
	TalentPoints          int32                  `protobuf:"varint,8,opt,name=talent_points,json=talentPoints,proto3" json:"talent_points,omitempty"`
	UnlockedStyles        []int32                `protobuf:"varint,9,rep,packed,name=unlocked_styles,json=unlockedStyles,proto3" json:"unlocked_styles,omitempty"`
	LastStyleId           int32                  `protobuf:"varint,10,opt,name=last_style_id,json=lastStyleId,proto3" json:"last_style_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PlayerArchive) Reset() {
	*x = PlayerArchive{}
	mi := &file_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerArchive) ProtoMessage() {}

func (x *PlayerArchive) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerArchive.ProtoReflect.Descriptor instead.
func (*PlayerArchive) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerArchive) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *PlayerArchive) GetGold() int32 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *PlayerArchive) GetExp() int32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *PlayerArchive) GetBestScore() int64 {
	if x != nil {
		return x.BestScore
	}
	return 0
}

func (x *PlayerArchive) GetTotalKills() int64 {
	if x != nil {
		return x.TotalKills
	}
	return 0
}

func (x *PlayerArchive) GetTotalGames() int64 {
	if x != nil {
		return x.TotalGames
	}
	return 0
}

func (x *PlayerArchive) GetHighestClearedDungeon() int32 {
	if x != nil {
		return x.HighestClearedDungeon
	}
	return 0
}

func (x *PlayerArchive) GetTalentPoints() int32 {
	if x != nil {
		return x.TalentPoints
	}
	return 0
}

func (x *PlayerArchive) GetUnlockedStyles() []int32 {
	if x != nil {
		return x.UnlockedStyles
	}
	return nil
}

func (x *PlayerArchive) GetLastStyleId() int32 {
	if x != nil {
		return x.LastStyleId
	}
	return 0
}

type SaveArchiveReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Archive       *PlayerArchive         `protobuf:"bytes,1,opt,name=archive,proto3" json:"archive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveArchiveReq) Reset() {
	*x = SaveArchiveReq{}
	mi := &file_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveArchiveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveArchiveReq) ProtoMessage() {}

func (x *SaveArchiveReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveArchiveReq.ProtoReflect.Descriptor instead.
func (*SaveArchiveReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{5}
}

func (x *SaveArchiveReq) GetArchive() *PlayerArchive {
	if x != nil {
		return x.Archive
	}
	return nil
}

type SaveArchiveResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveArchiveResp) Reset() {
	*x = SaveArchiveResp{}
	mi := &file_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveArchiveResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveArchiveResp) ProtoMessage() {}

func (x *SaveArchiveResp) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveArchiveResp.ProtoReflect.Descriptor instead.
func (*SaveArchiveResp) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{6}
}

func (x *SaveArchiveResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type LoadArchiveReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadArchiveReq) Reset() {
	*x = LoadArchiveReq{}
	mi := &file_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadArchiveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadArchiveReq) ProtoMessage() {}

func (x *LoadArchiveReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadArchiveReq.ProtoReflect.Descriptor instead.
func (*LoadArchiveReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{7}
}

type LoadArchiveResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Archive       *PlayerArchive         `protobuf:"bytes,2,opt,name=archive,proto3" json:"archive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadArchiveResp) Reset() {
	*x = LoadArchiveResp{}
	mi := &file_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadArchiveResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadArchiveResp) ProtoMessage() {}

func (x *LoadArchiveResp) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadArchiveResp.ProtoReflect.Descriptor instead.
func (*LoadArchiveResp) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{8}
}

func (x *LoadArchiveResp) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *LoadArchiveResp) GetArchive() *PlayerArchive {
	if x != nil {
		return x.Archive
	}
	return nil
}

type GetRankReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RankType      int32                  `protobuf:"varint,1,opt,name=rank_type,json=rankType,proto3" json:"rank_type,omitempty"`
	Start         int32                  `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRankReq) Reset() {
	*x = GetRankReq{}
	mi := &file_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRankReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRankReq) ProtoMessage() {}

func (x *GetRankReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRankReq.ProtoReflect.Descriptor instead.
func (*GetRankReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{9}
}

func (x *GetRankReq) GetRankType() int32 {
	if x != nil {
		return x.RankType
	}
	return 0
}

func (x *GetRankReq) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *GetRankReq) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type RankItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Score         int64                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	Rank          int32                  `protobuf:"varint,5,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankItem) Reset() {
	*x = RankItem{}
	mi := &file_game_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankItem) ProtoMessage() {}

func (x *RankItem) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankItem.ProtoReflect.Descriptor instead.
func (*RankItem) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{10}
}

func (x *RankItem) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *RankItem) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *RankItem) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *RankItem) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RankItem) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type GetRankResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ranks         []*RankItem            `protobuf:"bytes,1,rep,name=ranks,proto3" json:"ranks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRankResp) Reset() {
	*x = GetRankResp{}
	mi := &file_game_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRankResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRankResp) ProtoMessage() {}

func (x *GetRankResp) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRankResp.ProtoReflect.Descriptor instead.
func (*GetRankResp) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{11}
}

func (x *GetRankResp) GetRanks() []*RankItem {
	if x != nil {
		return x.Ranks
	}
	return nil
}

type ScoreMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DurationMs    int64                  `protobuf:"varint,1,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Kills         int32                  `protobuf:"varint,2,opt,name=kills,proto3" json:"kills,omitempty"`
	DungeonLevel  int32                  `protobuf:"varint,3,opt,name=dungeon_level,json=dungeonLevel,proto3" json:"dungeon_level,omitempty"`
	StyleId       int32                  `protobuf:"varint,4,opt,name=style_id,json=styleId,proto3" json:"style_id,omitempty"`
	PlayerLevel   int32                  `protobuf:"varint,5,opt,name=player_level,json=playerLevel,proto3" json:"player_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreMetadata) Reset() {
	*x = ScoreMetadata{}
	mi := &file_game_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreMetadata) ProtoMessage() {}

func (x *ScoreMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreMetadata.ProtoReflect.Descriptor instead.
func (*ScoreMetadata) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{12}
}

func (x *ScoreMetadata) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ScoreMetadata) GetKills() int32 {
	if x != nil {
		return x.Kills
	}
	return 0
}

func (x *ScoreMetadata) GetDungeonLevel() int32 {
	if x != nil {
		return x.DungeonLevel
	}
	return 0
}

func (x *ScoreMetadata) GetStyleId() int32 {
	if x != nil {
		return x.StyleId
	}
	return 0
}

func (x *ScoreMetadata) GetPlayerLevel() int32 {
	if x != nil {
		return x.PlayerLevel
	}
	return 0
}

type SubmitScoreReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         int64                  `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`
	Metadata      *ScoreMetadata         `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitScoreReq) Reset() {
	*x = SubmitScoreReq{}
	mi := &file_game_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitScoreReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitScoreReq) ProtoMessage() {}

func (x *SubmitScoreReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitScoreReq.ProtoReflect.Descriptor instead.
func (*SubmitScoreReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{13}
}

func (x *SubmitScoreReq) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SubmitScoreReq) GetMetadata() *ScoreMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SubmitScoreResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	BestScore     int64                  `protobuf:"varint,2,opt,name=best_score,json=bestScore,proto3" json:"best_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitScoreResp) Reset() {
	*x = SubmitScoreResp{}
	mi := &file_game_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitScoreResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitScoreResp) ProtoMessage() {}

func (x *SubmitScoreResp) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitScoreResp.ProtoReflect.Descriptor instead.
func (*SubmitScoreResp) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{14}
}

func (x *SubmitScoreResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubmitScoreResp) GetBestScore() int64 {
	if x != nil {
		return x.BestScore
	}
	return 0
}

type CombatResultReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	DungeonLevel  int32                  `protobuf:"varint,2,opt,name=dungeon_level,json=dungeonLevel,proto3" json:"dungeon_level,omitempty"`
	Score         int64                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	Kills         int32                  `protobuf:"varint,4,opt,name=kills,proto3" json:"kills,omitempty"`
	SurvivalTime  float64                `protobuf:"fixed64,5,opt,name=survival_time,json=survivalTime,proto3" json:"survival_time,omitempty"`
	StyleId       int32                  `protobuf:"varint,6,opt,name=style_id,json=styleId,proto3" json:"style_id,omitempty"`
	Outcome       BattleOutcome          `protobuf:"varint,7,opt,name=outcome,proto3,enum=game.protocol.v1.BattleOutcome" json:"outcome,omitempty"`
	PlayerLevel   int32                  `protobuf:"varint,8,opt,name=player_level,json=playerLevel,proto3" json:"player_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombatResultReq) Reset() {
	*x = CombatResultReq{}
	mi := &file_game_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombatResultReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatResultReq) ProtoMessage() {}

func (x *CombatResultReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatResultReq.ProtoReflect.Descriptor instead.
func (*CombatResultReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{15}
}

func (x *CombatResultReq) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *CombatResultReq) GetDungeonLevel() int32 {
	if x != nil {
		return x.DungeonLevel
	}
	return 0
}

func (x *CombatResultReq) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *CombatResultReq) GetKills() int32 {
	if x != nil {
		return x.Kills
	}
	return 0
}

func (x *CombatResultReq) GetSurvivalTime() float64 {
	if x != nil {
		return x.SurvivalTime
	}
	return 0
}

func (x *CombatResultReq) GetStyleId() int32 {
	if x != nil {
		return x.StyleId
	}
	return 0
}

func (x *CombatResultReq) GetOutcome() BattleOutcome {
	if x != nil {
		return x.Outcome
	}
	return BattleOutcome_BATTLE_OUTCOME_UNSPECIFIED
}

func (x *CombatResultReq) GetPlayerLevel() int32 {
	if x != nil {
		return x.PlayerLevel
	}
	return 0
}

type CombatResultResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Duplicate     bool                   `protobuf:"varint,2,opt,name=duplicate,proto3" json:"duplicate,omitempty"`
	RewardGold    int32                  `protobuf:"varint,3,opt,name=reward_gold,json=rewardGold,proto3" json:"reward_gold,omitempty"`
	RewardExp     int32                  `protobuf:"varint,4,opt,name=reward_exp,json=rewardExp,proto3" json:"reward_exp,omitempty"`
	BestScore     int64                  `protobuf:"varint,5,opt,name=best_score,json=bestScore,proto3" json:"best_score,omitempty"`
	Archive       *PlayerArchive         `protobuf:"bytes,6,opt,name=archive,proto3" json:"archive,omitempty"`
	RunId         string                 `protobuf:"bytes,7,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombatResultResp) Reset() {
	*x = CombatResultResp{}
	mi := &file_game_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombatResultResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatResultResp) ProtoMessage() {}

func (x *CombatResultResp) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatResultResp.ProtoReflect.Descriptor instead.
func (*CombatResultResp) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{16}
}

func (x *CombatResultResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CombatResultResp) GetDuplicate() bool {
	if x != nil {
		return x.Duplicate
	}
	return false
}

func (x *CombatResultResp) GetRewardGold() int32 {
	if x != nil {
		return x.RewardGold
	}
	return 0
}

func (x *CombatResultResp) GetRewardExp() int32 {
	if x != nil {
		return x.RewardExp
	}
	return 0
}

func (x *CombatResultResp) GetBestScore() int64 {
	if x != nil {
		return x.BestScore
	}
	return 0
}

func (x *CombatResultResp) GetArchive() *PlayerArchive {
	if x != nil {
		return x.Archive
	}
	return nil
}

func (x *CombatResultResp) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type EnemyConfigItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Hp            int32                  `protobuf:"varint,3,opt,name=hp,proto3" json:"hp,omitempty"`
	Damage        int32                  `protobuf:"varint,4,opt,name=damage,proto3" json:"damage,omitempty"`
	Speed         float32                `protobuf:"fixed32,5,opt,name=speed,proto3" json:"speed,omitempty"`
	AttackRange   float32                `protobuf:"fixed32,6,opt,name=attack_range,json=attackRange,proto3" json:"attack_range,omitempty"`
	EnemyType     string                 `protobuf:"bytes,7,opt,name=enemy_type,json=enemyType,proto3" json:"enemy_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnemyConfigItem) Reset() {
	*x = EnemyConfigItem{}
	mi := &file_game_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnemyConfigItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnemyConfigItem) ProtoMessage() {}

func (x *EnemyConfigItem) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnemyConfigItem.ProtoReflect.Descriptor instead.
func (*EnemyConfigItem) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{17}
}

func (x *EnemyConfigItem) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EnemyConfigItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnemyConfigItem) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *EnemyConfigItem) GetDamage() int32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *EnemyConfigItem) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *EnemyConfigItem) GetAttackRange() float32 {
	if x != nil {
		return x.AttackRange
	}
	return 0
}

func (x *EnemyConfigItem) GetEnemyType() string {
	if x != nil {
		return x.EnemyType
	}
	return ""
}

type GetEnemyConfigsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnemyConfigsReq) Reset() {
	*x = GetEnemyConfigsReq{}
	mi := &file_game_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnemyConfigsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnemyConfigsReq) ProtoMessage() {}

func (x *GetEnemyConfigsReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnemyConfigsReq.ProtoReflect.Descriptor instead.
func (*GetEnemyConfigsReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{18}
}

type GetEnemyConfigsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       []*EnemyConfigItem     `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnemyConfigsResp) Reset() {
	*x = GetEnemyConfigsResp{}
	mi := &file_game_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnemyConfigsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnemyConfigsResp) ProtoMessage() {}

func (x *GetEnemyConfigsResp) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnemyConfigsResp.ProtoReflect.Descriptor instead.
func (*GetEnemyConfigsResp) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{19}
}

func (x *GetEnemyConfigsResp) GetConfigs() []*EnemyConfigItem {
	if x != nil {
		return x.Configs
	}
	return nil
}

type DungeonConfigItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         int32                  `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	RoomCount     int32                  `protobuf:"varint,2,opt,name=room_count,json=roomCount,proto3" json:"room_count,omitempty"`
	EnemyDensity  float32                `protobuf:"fixed32,3,opt,name=enemy_density,json=enemyDensity,proto3" json:"enemy_density,omitempty"`
	BossId        int32                  `protobuf:"varint,4,opt,name=boss_id,json=bossId,proto3" json:"boss_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DungeonConfigItem) Reset() {
	*x = DungeonConfigItem{}
	mi := &file_game_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DungeonConfigItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DungeonConfigItem) ProtoMessage() {}

func (x *DungeonConfigItem) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DungeonConfigItem.ProtoReflect.Descriptor instead.
func (*DungeonConfigItem) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{20}
}

func (x *DungeonConfigItem) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *DungeonConfigItem) GetRoomCount() int32 {
	if x != nil {
		return x.RoomCount
	}
	return 0
}

func (x *DungeonConfigItem) GetEnemyDensity() float32 {
	if x != nil {
		return x.EnemyDensity
	}
	return 0
}

func (x *DungeonConfigItem) GetBossId() int32 {
	if x != nil {
		return x.BossId
	}
	return 0
}

type GetDungeonConfigReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         int32                  `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDungeonConfigReq) Reset() {
	*x = GetDungeonConfigReq{}
	mi := &file_game_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDungeonConfigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDungeonConfigReq) ProtoMessage() {}

func (x *GetDungeonConfigReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDungeonConfigReq.ProtoReflect.Descriptor instead.
func (*GetDungeonConfigReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{21}
}

func (x *GetDungeonConfigReq) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type GetDungeonConfigResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         int32                  `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	RoomCount     int32                  `protobuf:"varint,2,opt,name=room_count,json=roomCount,proto3" json:"room_count,omitempty"`
	EnemyDensity  float32                `protobuf:"fixed32,3,opt,name=enemy_density,json=enemyDensity,proto3" json:"enemy_density,omitempty"`
	BossId        int32                  `protobuf:"varint,4,opt,name=boss_id,json=bossId,proto3" json:"boss_id,omitempty"`
	EnemyConfigs  []*EnemyConfigItem     `protobuf:"bytes,5,rep,name=enemy_configs,json=enemyConfigs,proto3" json:"enemy_configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDungeonConfigResp) Reset() {
	*x = GetDungeonConfigResp{}
	mi := &file_game_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDungeonConfigResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDungeonConfigResp) ProtoMessage() {}

func (x *GetDungeonConfigResp) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDungeonConfigResp.ProtoReflect.Descriptor instead.
func (*GetDungeonConfigResp) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{22}
}

func (x *GetDungeonConfigResp) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *GetDungeonConfigResp) GetRoomCount() int32 {
	if x != nil {
		return x.RoomCount
	}
	return 0
}

func (x *GetDungeonConfigResp) GetEnemyDensity() float32 {
	if x != nil {
		return x.EnemyDensity
	}
	return 0
}

func (x *GetDungeonConfigResp) GetBossId() int32 {
	if x != nil {
		return x.BossId
	}
	return 0
}

func (x *GetDungeonConfigResp) GetEnemyConfigs() []*EnemyConfigItem {
	if x != nil {
		return x.EnemyConfigs
	}
	return nil
}

type StyleConfigItem struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	StyleId             int32                  `protobuf:"varint,1,opt,name=style_id,json=styleId,proto3" json:"style_id,omitempty"`
	StyleName           string                 `protobuf:"bytes,2,opt,name=style_name,json=styleName,proto3" json:"style_name,omitempty"`
	DamageMult          float32                `protobuf:"fixed32,3,opt,name=damage_mult,json=damageMult,proto3" json:"damage_mult,omitempty"`
	SpeedMult           float32                `protobuf:"fixed32,4,opt,name=speed_mult,json=speedMult,proto3" json:"speed_mult,omitempty"`
	ParryMult           float32                `protobuf:"fixed32,5,opt,name=parry_mult,json=parryMult,proto3" json:"parry_mult,omitempty"`
	DashSpeedMult       float32                `protobuf:"fixed32,6,opt,name=dash_speed_mult,json=dashSpeedMult,proto3" json:"dash_speed_mult,omitempty"`
	DashCostMult        float32                `protobuf:"fixed32,7,opt,name=dash_cost_mult,json=dashCostMult,proto3" json:"dash_cost_mult,omitempty"`
	SpecialResourceMax  int32                  `protobuf:"varint,8,opt,name=special_resource_max,json=specialResourceMax,proto3" json:"special_resource_max,omitempty"`
	SpecialResourceName string                 `protobuf:"bytes,9,opt,name=special_resource_name,json=specialResourceName,proto3" json:"special_resource_name,omitempty"`
	Description         string                 `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StyleConfigItem) Reset() {
	*x = StyleConfigItem{}
	mi := &file_game_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StyleConfigItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StyleConfigItem) ProtoMessage() {}

func (x *StyleConfigItem) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StyleConfigItem.ProtoReflect.Descriptor instead.
func (*StyleConfigItem) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{23}
}

func (x *StyleConfigItem) GetStyleId() int32 {
	if x != nil {
		return x.StyleId
	}
	return 0
}

func (x *StyleConfigItem) GetStyleName() string {
	if x != nil {
		return x.StyleName
	}
	return ""
}

func (x *StyleConfigItem) GetDamageMult() float32 {
	if x != nil {
		return x.DamageMult
	}
	return 0
}

func (x *StyleConfigItem) GetSpeedMult() float32 {
	if x != nil {
		return x.SpeedMult
	}
	return 0
}

func (x *StyleConfigItem) GetParryMult() float32 {
	if x != nil {
		return x.ParryMult
	}
	return 0
}

func (x *StyleConfigItem) GetDashSpeedMult() float32 {
	if x != nil {
		return x.DashSpeedMult
	}
	return 0
}

func (x *StyleConfigItem) GetDashCostMult() float32 {
	if x != nil {
		return x.DashCostMult
	}
	return 0
}

func (x *StyleConfigItem) GetSpecialResourceMax() int32 {
	if x != nil {
		return x.SpecialResourceMax
	}
	return 0
}

func (x *StyleConfigItem) GetSpecialResourceName() string {
	if x != nil {
		return x.SpecialResourceName
	}
	return ""
}

func (x *StyleConfigItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetStyleConfigsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStyleConfigsReq) Reset() {
	*x = GetStyleConfigsReq{}
	mi := &file_game_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStyleConfigsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStyleConfigsReq) ProtoMessage() {}

func (x *GetStyleConfigsReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStyleConfigsReq.ProtoReflect.Descriptor instead.
func (*GetStyleConfigsReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{24}
}

type GetStyleConfigsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Styles        []*StyleConfigItem     `protobuf:"bytes,1,rep,name=styles,proto3" json:"styles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStyleConfigsResp) Reset() {
	*x = GetStyleConfigsResp{}
	mi := &file_game_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStyleConfigsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStyleConfigsResp) ProtoMessage() {}

func (x *GetStyleConfigsResp) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStyleConfigsResp.ProtoReflect.Descriptor instead.
func (*GetStyleConfigsResp) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{25}
}

func (x *GetStyleConfigsResp) GetStyles() []*StyleConfigItem {
	if x != nil {
		return x.Styles
	}
	return nil
}

type UnlockStyleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StyleId       int32                  `protobuf:"varint,1,opt,name=style_id,json=styleId,proto3" json:"style_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockStyleReq) Reset() {
	*x = UnlockStyleReq{}
	mi := &file_game_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockStyleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockStyleReq) ProtoMessage() {}

func (x *UnlockStyleReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockStyleReq.ProtoReflect.Descriptor instead.
func (*UnlockStyleReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{26}
}

func (x *UnlockStyleReq) GetStyleId() int32 {
	if x != nil {
		return x.StyleId
	}
	return 0
}

type UnlockStyleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	GoldCost      int32                  `protobuf:"varint,2,opt,name=gold_cost,json=goldCost,proto3" json:"gold_cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockStyleResp) Reset() {
	*x = UnlockStyleResp{}
	mi := &file_game_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockStyleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockStyleResp) ProtoMessage() {}

func (x *UnlockStyleResp) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockStyleResp.ProtoReflect.Descriptor instead.
func (*UnlockStyleResp) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{27}
}

func (x *UnlockStyleResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnlockStyleResp) GetGoldCost() int32 {
	if x != nil {
		return x.GoldCost
	}
	return 0
}

type PlayerStatsData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Level          int32                  `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	Exp            int32                  `protobuf:"varint,2,opt,name=exp,proto3" json:"exp,omitempty"`
	Gold           int32                  `protobuf:"varint,3,opt,name=gold,proto3" json:"gold,omitempty"`
	MaxHp          int32                  `protobuf:"varint,4,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	MaxStamina     int32                  `protobuf:"varint,5,opt,name=max_stamina,json=maxStamina,proto3" json:"max_stamina,omitempty"`
	AttackPower    int32                  `protobuf:"varint,6,opt,name=attack_power,json=attackPower,proto3" json:"attack_power,omitempty"`
	UnlockedStyles []int32                `protobuf:"varint,7,rep,packed,name=unlocked_styles,json=unlockedStyles,proto3" json:"unlocked_styles,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlayerStatsData) Reset() {
	*x = PlayerStatsData{}
	mi := &file_game_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerStatsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerStatsData) ProtoMessage() {}

func (x *PlayerStatsData) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerStatsData.ProtoReflect.Descriptor instead.
func (*PlayerStatsData) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{28}
}

func (x *PlayerStatsData) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PlayerStatsData) GetExp() int32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *PlayerStatsData) GetGold() int32 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *PlayerStatsData) GetMaxHp() int32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *PlayerStatsData) GetMaxStamina() int32 {
	if x != nil {
		return x.MaxStamina
	}
	return 0
}

func (x *PlayerStatsData) GetAttackPower() int32 {
	if x != nil {
		return x.AttackPower
	}
	return 0
}

func (x *PlayerStatsData) GetUnlockedStyles() []int32 {
	if x != nil {
		return x.UnlockedStyles
	}
	return nil
}

type GetPlayerStatsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerStatsReq) Reset() {
	*x = GetPlayerStatsReq{}
	mi := &file_game_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerStatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerStatsReq) ProtoMessage() {}

func (x *GetPlayerStatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerStatsReq.ProtoReflect.Descriptor instead.
func (*GetPlayerStatsReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{29}
}

type GetPlayerStatsResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Level          int32                  `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	Exp            int32                  `protobuf:"varint,2,opt,name=exp,proto3" json:"exp,omitempty"`
	Gold           int32                  `protobuf:"varint,3,opt,name=gold,proto3" json:"gold,omitempty"`
	MaxHp          int32                  `protobuf:"varint,4,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	MaxStamina     int32                  `protobuf:"varint,5,opt,name=max_stamina,json=maxStamina,proto3" json:"max_stamina,omitempty"`
	AttackPower    int32                  `protobuf:"varint,6,opt,name=attack_power,json=attackPower,proto3" json:"attack_power,omitempty"`
	UnlockedStyles []int32                `protobuf:"varint,7,rep,packed,name=unlocked_styles,json=unlockedStyles,proto3" json:"unlocked_styles,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetPlayerStatsResp) Reset() {
	*x = GetPlayerStatsResp{}
	mi := &file_game_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerStatsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerStatsResp) ProtoMessage() {}

func (x *GetPlayerStatsResp) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerStatsResp.ProtoReflect.Descriptor instead.
func (*GetPlayerStatsResp) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{30}
}

func (x *GetPlayerStatsResp) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *GetPlayerStatsResp) GetExp() int32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *GetPlayerStatsResp) GetGold() int32 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *GetPlayerStatsResp) GetMaxHp() int32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *GetPlayerStatsResp) GetMaxStamina() int32 {
	if x != nil {
		return x.MaxStamina
	}
	return 0
}

func (x *GetPlayerStatsResp) GetAttackPower() int32 {
	if x != nil {
		return x.AttackPower
	}
	return 0
}

func (x *GetPlayerStatsResp) GetUnlockedStyles() []int32 {
	if x != nil {
		return x.UnlockedStyles
	}
	return nil
}

type UpdatePlayerStatsReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Level          int32                  `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	Exp            int32                  `protobuf:"varint,2,opt,name=exp,proto3" json:"exp,omitempty"`
	Gold           int32                  `protobuf:"varint,3,opt,name=gold,proto3" json:"gold,omitempty"`
	MaxHp          int32                  `protobuf:"varint,4,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	MaxStamina     int32                  `protobuf:"varint,5,opt,name=max_stamina,json=maxStamina,proto3" json:"max_stamina,omitempty"`
	AttackPower    int32                  `protobuf:"varint,6,opt,name=attack_power,json=attackPower,proto3" json:"attack_power,omitempty"`
	UnlockedStyles []int32                `protobuf:"varint,7,rep,packed,name=unlocked_styles,json=unlockedStyles,proto3" json:"unlocked_styles,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdatePlayerStatsReq) Reset() {
	*x = UpdatePlayerStatsReq{}
	mi := &file_game_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlayerStatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlayerStatsReq) ProtoMessage() {}

func (x *UpdatePlayerStatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlayerStatsReq.ProtoReflect.Descriptor instead.
func (*UpdatePlayerStatsReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{31}
}

func (x *UpdatePlayerStatsReq) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *UpdatePlayerStatsReq) GetExp() int32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *UpdatePlayerStatsReq) GetGold() int32 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *UpdatePlayerStatsReq) GetMaxHp() int32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *UpdatePlayerStatsReq) GetMaxStamina() int32 {
	if x != nil {
		return x.MaxStamina
	}
	return 0
}

func (x *UpdatePlayerStatsReq) GetAttackPower() int32 {
	if x != nil {
		return x.AttackPower
	}
	return 0
}

func (x *UpdatePlayerStatsReq) GetUnlockedStyles() []int32 {
	if x != nil {
		return x.UnlockedStyles
	}
	return nil
}

type UpdatePlayerStatsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlayerStatsResp) Reset() {
	*x = UpdatePlayerStatsResp{}
	mi := &file_game_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlayerStatsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlayerStatsResp) ProtoMessage() {}

func (x *UpdatePlayerStatsResp) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlayerStatsResp.ProtoReflect.Descriptor instead.
func (*UpdatePlayerStatsResp) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{32}
}

func (x *UpdatePlayerStatsResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CreateOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderReq) Reset() {
	*x = CreateOrderReq{}
	mi := &file_game_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderReq) ProtoMessage() {}

func (x *CreateOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderReq.ProtoReflect.Descriptor instead.
func (*CreateOrderReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{33}
}

func (x *CreateOrderReq) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type CreateOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResp) Reset() {
	*x = CreateOrderResp{}
	mi := &file_game_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResp) ProtoMessage() {}

func (x *CreateOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResp.ProtoReflect.Descriptor instead.
func (*CreateOrderResp) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{34}
}

func (x *CreateOrderResp) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type PayResultNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ProductId     int32                  `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayResultNotify) Reset() {
	*x = PayResultNotify{}
	mi := &file_game_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayResultNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayResultNotify) ProtoMessage() {}

func (x *PayResultNotify) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayResultNotify.ProtoReflect.Descriptor instead.
func (*PayResultNotify) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{35}
}

func (x *PayResultNotify) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *PayResultNotify) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PayResultNotify) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type GMCommandReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmd           string                 `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	ArgsJson      []byte                 `protobuf:"bytes,2,opt,name=args_json,json=argsJson,proto3" json:"args_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GMCommandReq) Reset() {
	*x = GMCommandReq{}
	mi := &file_game_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GMCommandReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GMCommandReq) ProtoMessage() {}

func (x *GMCommandReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GMCommandReq.ProtoReflect.Descriptor instead.
func (*GMCommandReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{36}
}

func (x *GMCommandReq) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *GMCommandReq) GetArgsJson() []byte {
	if x != nil {
		return x.ArgsJson
	}
	return nil
}

type GMCommandResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmd           string                 `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Result        string                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GMCommandResp) Reset() {
	*x = GMCommandResp{}
	mi := &file_game_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GMCommandResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GMCommandResp) ProtoMessage() {}

func (x *GMCommandResp) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GMCommandResp.ProtoReflect.Descriptor instead.
func (*GMCommandResp) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{37}
}

func (x *GMCommandResp) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *GMCommandResp) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type ErrorResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResp) Reset() {
	*x = ErrorResp{}
	mi := &file_game_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResp) ProtoMessage() {}

func (x *ErrorResp) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResp.ProtoReflect.Descriptor instead.
func (*ErrorResp) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{38}
}

func (x *ErrorResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_game_proto protoreflect.FileDescriptor

const file_game_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"game.proto\x12\x10game.protocol.v1\"\x1e\n" +
	"\bLoginReq\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"O\n" +
	"\tLoginResp\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\",\n" +
	"\fHeartbeatReq\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"-\n" +
	"\rHeartbeatResp\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"\xe7\x02\n" +
	"\rPlayerArchive\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\x05R\rschemaVersion\x12\x12\n" +
	"\x04gold\x18\x02 \x01(\x05R\x04gold\x12\x10\n" +
	"\x03exp\x18\x03 \x01(\x05R\x03exp\x12\x1d\n" +
	"\n" +
	"best_score\x18\x04 \x01(\x03R\tbestScore\x12\x1f\n" +
	"\vtotal_kills\x18\x05 \x01(\x03R\n" +
	"totalKills\x12\x1f\n" +
	"\vtotal_games\x18\x06 \x01(\x03R\n" +
	"totalGames\x126\n" +
	"\x17highest_cleared_dungeon\x18\a \x01(\x05R\x15highestClearedDungeon\x12#\n" +
	"\rtalent_points\x18\b \x01(\x05R\ftalentPoints\x12'\n" +
	"\x0funlocked_styles\x18\t \x03(\x05R\x0eunlockedStyles\x12\"\n" +
	"\rlast_style_id\x18\n" +
	" \x01(\x05R\vlastStyleId\"K\n" +
	"\x0eSaveArchiveReq\x129\n" +
	"\aarchive\x18\x01 \x01(\v2\x1f.game.protocol.v1.PlayerArchiveR\aarchive\"+\n" +
	"\x0fSaveArchiveResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x10\n" +
	"\x0eLoadArchiveReq\"b\n" +
	"\x0fLoadArchiveResp\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x129\n" +
	"\aarchive\x18\x02 \x01(\v2\x1f.game.protocol.v1.PlayerArchiveR\aarchive\"U\n" +
	"\n" +
	"GetRankReq\x12\x1b\n" +
	"\trank_type\x18\x01 \x01(\x05R\brankType\x12\x14\n" +
	"\x05start\x18\x02 \x01(\x05R\x05start\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"x\n" +
	"\bRankItem\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x03R\x05score\x12\x12\n" +
	"\x04rank\x18\x05 \x01(\x05R\x04rank\"?\n" +
	"\vGetRankResp\x120\n" +
	"\x05ranks\x18\x01 \x03(\v2\x1a.game.protocol.v1.RankItemR\x05ranks\"\xa9\x01\n" +
	"\rScoreMetadata\x12\x1f\n" +
	"\vduration_ms\x18\x01 \x01(\x03R\n" +
	"durationMs\x12\x14\n" +
	"\x05kills\x18\x02 \x01(\x05R\x05kills\x12#\n" +
	"\rdungeon_level\x18\x03 \x01(\x05R\fdungeonLevel\x12\x19\n" +
	"\bstyle_id\x18\x04 \x01(\x05R\astyleId\x12!\n" +
	"\fplayer_level\x18\x05 \x01(\x05R\vplayerLevel\"c\n" +
	"\x0eSubmitScoreReq\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x03R\x05score\x12;\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1f.game.protocol.v1.ScoreMetadataR\bmetadata\"J\n" +
	"\x0fSubmitScoreResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"best_score\x18\x02 \x01(\x03R\tbestScore\"\x97\x02\n" +
	"\x0fCombatResultReq\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12#\n" +
	"\rdungeon_level\x18\x02 \x01(\x05R\fdungeonLevel\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x03R\x05score\x12\x14\n" +
	"\x05kills\x18\x04 \x01(\x05R\x05kills\x12#\n" +
	"\rsurvival_time\x18\x05 \x01(\x01R\fsurvivalTime\x12\x19\n" +
	"\bstyle_id\x18\x06 \x01(\x05R\astyleId\x129\n" +
	"\aoutcome\x18\a \x01(\x0e2\x1f.game.protocol.v1.BattleOutcomeR\aoutcome\x12!\n" +
	"\fplayer_level\x18\b \x01(\x05R\vplayerLevel\"\xfb\x01\n" +
	"\x10CombatResultResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1c\n" +
	"\tduplicate\x18\x02 \x01(\bR\tduplicate\x12\x1f\n" +
	"\vreward_gold\x18\x03 \x01(\x05R\n" +
	"rewardGold\x12\x1d\n" +
	"\n" +
	"reward_exp\x18\x04 \x01(\x05R\trewardExp\x12\x1d\n" +
	"\n" +
	"best_score\x18\x05 \x01(\x03R\tbestScore\x129\n" +
	"\aarchive\x18\x06 \x01(\v2\x1f.game.protocol.v1.PlayerArchiveR\aarchive\x12\x15\n" +
	"\x06run_id\x18\a \x01(\tR\x05runId\"\xb5\x01\n" +
	"\x0fEnemyConfigItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x0e\n" +
	"\x02hp\x18\x03 \x01(\x05R\x02hp\x12\x16\n" +
	"\x06damage\x18\x04 \x01(\x05R\x06damage\x12\x14\n" +
	"\x05speed\x18\x05 \x01(\x02R\x05speed\x12!\n" +
	"\fattack_range\x18\x06 \x01(\x02R\vattackRange\x12\x1d\n" +
	"\n" +
	"enemy_type\x18\a \x01(\tR\tenemyType\"\x14\n" +
	"\x12GetEnemyConfigsReq\"R\n" +
	"\x13GetEnemyConfigsResp\x12;\n" +
	"\aconfigs\x18\x01 \x03(\v2!.game.protocol.v1.EnemyConfigItemR\aconfigs\"\x86\x01\n" +
	"\x11DungeonConfigItem\x12\x14\n" +
	"\x05level\x18\x01 \x01(\x05R\x05level\x12\x1d\n" +
	"\n" +
	"room_count\x18\x02 \x01(\x05R\troomCount\x12#\n" +
	"\renemy_density\x18\x03 \x01(\x02R\fenemyDensity\x12\x17\n" +
	"\aboss_id\x18\x04 \x01(\x05R\x06bossId\"+\n" +
	"\x13GetDungeonConfigReq\x12\x14\n" +
	"\x05level\x18\x01 \x01(\x05R\x05level\"\xd1\x01\n" +
	"\x14GetDungeonConfigResp\x12\x14\n" +
	"\x05level\x18\x01 \x01(\x05R\x05level\x12\x1d\n" +
	"\n" +
	"room_count\x18\x02 \x01(\x05R\troomCount\x12#\n" +
	"\renemy_density\x18\x03 \x01(\x02R\fenemyDensity\x12\x17\n" +
	"\aboss_id\x18\x04 \x01(\x05R\x06bossId\x12F\n" +
	"\renemy_configs\x18\x05 \x03(\v2!.game.protocol.v1.EnemyConfigItemR\fenemyConfigs\"\x80\x03\n" +
	"\x0fStyleConfigItem\x12\x19\n" +
	"\bstyle_id\x18\x01 \x01(\x05R\astyleId\x12\x1d\n" +
	"\n" +
	"style_name\x18\x02 \x01(\tR\tstyleName\x12\x1f\n" +
	"\vdamage_mult\x18\x03 \x01(\x02R\n" +
	"damageMult\x12\x1d\n" +
	"\n" +
	"speed_mult\x18\x04 \x01(\x02R\tspeedMult\x12\x1d\n" +
	"\n" +
	"parry_mult\x18\x05 \x01(\x02R\tparryMult\x12&\n" +
	"\x0fdash_speed_mult\x18\x06 \x01(\x02R\rdashSpeedMult\x12$\n" +
	"\x0edash_cost_mult\x18\a \x01(\x02R\fdashCostMult\x120\n" +
	"\x14special_resource_max\x18\b \x01(\x05R\x12specialResourceMax\x122\n" +
	"\x15special_resource_name\x18\t \x01(\tR\x13specialResourceName\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\"\x14\n" +
	"\x12GetStyleConfigsReq\"P\n" +
	"\x13GetStyleConfigsResp\x129\n" +
	"\x06styles\x18\x01 \x03(\v2!.game.protocol.v1.StyleConfigItemR\x06styles\"+\n" +
	"\x0eUnlockStyleReq\x12\x19\n" +
	"\bstyle_id\x18\x01 \x01(\x05R\astyleId\"H\n" +
	"\x0fUnlockStyleResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\tgold_cost\x18\x02 \x01(\x05R\bgoldCost\"\xd1\x01\n" +
	"\x0fPlayerStatsData\x12\x14\n" +
	"\x05level\x18\x01 \x01(\x05R\x05level\x12\x10\n" +
	"\x03exp\x18\x02 \x01(\x05R\x03exp\x12\x12\n" +
	"\x04gold\x18\x03 \x01(\x05R\x04gold\x12\x15\n" +
	"\x06max_hp\x18\x04 \x01(\x05R\x05maxHp\x12\x1f\n" +
	"\vmax_stamina\x18\x05 \x01(\x05R\n" +
	"maxStamina\x12!\n" +
	"\fattack_power\x18\x06 \x01(\x05R\vattackPower\x12'\n" +
	"\x0funlocked_styles\x18\a \x03(\x05R\x0eunlockedStyles\"\x13\n" +
	"\x11GetPlayerStatsReq\"\xd4\x01\n" +
	"\x12GetPlayerStatsResp\x12\x14\n" +
	"\x05level\x18\x01 \x01(\x05R\x05level\x12\x10\n" +
	"\x03exp\x18\x02 \x01(\x05R\x03exp\x12\x12\n" +
	"\x04gold\x18\x03 \x01(\x05R\x04gold\x12\x15\n" +
	"\x06max_hp\x18\x04 \x01(\x05R\x05maxHp\x12\x1f\n" +
	"\vmax_stamina\x18\x05 \x01(\x05R\n" +
	"maxStamina\x12!\n" +
	"\fattack_power\x18\x06 \x01(\x05R\vattackPower\x12'\n" +
	"\x0funlocked_styles\x18\a \x03(\x05R\x0eunlockedStyles\"\xd6\x01\n" +
	"\x14UpdatePlayerStatsReq\x12\x14\n" +
	"\x05level\x18\x01 \x01(\x05R\x05level\x12\x10\n" +
	"\x03exp\x18\x02 \x01(\x05R\x03exp\x12\x12\n" +
	"\x04gold\x18\x03 \x01(\x05R\x04gold\x12\x15\n" +
	"\x06max_hp\x18\x04 \x01(\x05R\x05maxHp\x12\x1f\n" +
	"\vmax_stamina\x18\x05 \x01(\x05R\n" +
	"maxStamina\x12!\n" +
	"\fattack_power\x18\x06 \x01(\x05R\vattackPower\x12'\n" +
	"\x0funlocked_styles\x18\a \x03(\x05R\x0eunlockedStyles\"1\n" +
	"\x15UpdatePlayerStatsResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"/\n" +
	"\x0eCreateOrderReq\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x05R\tproductId\",\n" +
	"\x0fCreateOrderResp\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\"c\n" +
	"\x0fPayResultNotify\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x05R\tproductId\"=\n" +
	"\fGMCommandReq\x12\x10\n" +
	"\x03cmd\x18\x01 \x01(\tR\x03cmd\x12\x1b\n" +
	"\targs_json\x18\x02 \x01(\fR\bargsJson\"9\n" +
	"\rGMCommandResp\x12\x10\n" +
	"\x03cmd\x18\x01 \x01(\tR\x03cmd\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\"1\n" +
	"\tErrorResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg*\x84\t\n" +
	"\tMessageId\x12\x1a\n" +
	"\x16MESSAGE_ID_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x14MESSAGE_ID_LOGIN_REQ\x10\xe9\a\x12\x1a\n" +
	"\x15MESSAGE_ID_LOGIN_RESP\x10\xea\a\x12\x1d\n" +
	"\x18MESSAGE_ID_HEARTBEAT_REQ\x10\xeb\a\x12\x1e\n" +
	"\x19MESSAGE_ID_HEARTBEAT_RESP\x10\xec\a\x12 \n" +
	"\x1bMESSAGE_ID_SAVE_ARCHIVE_REQ\x10\xd1\x0f\x12!\n" +
	"\x1cMESSAGE_ID_SAVE_ARCHIVE_RESP\x10\xd2\x0f\x12 \n" +
	"\x1bMESSAGE_ID_LOAD_ARCHIVE_REQ\x10\xd3\x0f\x12!\n" +
	"\x1cMESSAGE_ID_LOAD_ARCHIVE_RESP\x10\xd4\x0f\x12\x1c\n" +
	"\x17MESSAGE_ID_GET_RANK_REQ\x10\xb9\x17\x12\x1d\n" +
	"\x18MESSAGE_ID_GET_RANK_RESP\x10\xba\x17\x12 \n" +
	"\x1bMESSAGE_ID_SUBMIT_SCORE_REQ\x10\xbb\x17\x12!\n" +
	"\x1cMESSAGE_ID_SUBMIT_SCORE_RESP\x10\xbc\x17\x12!\n" +
	"\x1cMESSAGE_ID_COMBAT_RESULT_REQ\x10\xa1\x1f\x12\"\n" +
	"\x1dMESSAGE_ID_COMBAT_RESULT_RESP\x10\xa2\x1f\x12%\n" +
	" MESSAGE_ID_GET_ENEMY_CONFIGS_REQ\x10\xa3\x1f\x12&\n" +
	"!MESSAGE_ID_GET_ENEMY_CONFIGS_RESP\x10\xa4\x1f\x12&\n" +
	"!MESSAGE_ID_GET_DUNGEON_CONFIG_REQ\x10\xa5\x1f\x12'\n" +
	"\"MESSAGE_ID_GET_DUNGEON_CONFIG_RESP\x10\xa6\x1f\x12%\n" +
	" MESSAGE_ID_GET_STYLE_CONFIGS_REQ\x10\xa7\x1f\x12&\n" +
	"!MESSAGE_ID_GET_STYLE_CONFIGS_RESP\x10\xa8\x1f\x12 \n" +
	"\x1bMESSAGE_ID_UNLOCK_STYLE_REQ\x10\xa9\x1f\x12!\n" +
	"\x1cMESSAGE_ID_UNLOCK_STYLE_RESP\x10\xaa\x1f\x12$\n" +
	"\x1fMESSAGE_ID_GET_PLAYER_STATS_REQ\x10\xab\x1f\x12%\n" +
	" MESSAGE_ID_GET_PLAYER_STATS_RESP\x10\xac\x1f\x12'\n" +
	"\"MESSAGE_ID_UPDATE_PLAYER_STATS_REQ\x10\xad\x1f\x12(\n" +
	"#MESSAGE_ID_UPDATE_PLAYER_STATS_RESP\x10\xae\x1f\x12 \n" +
	"\x1bMESSAGE_ID_CREATE_ORDER_REQ\x10\x89'\x12!\n" +
	"\x1cMESSAGE_ID_CREATE_ORDER_RESP\x10\x8a'\x12!\n" +
	"\x1cMESSAGE_ID_PAY_RESULT_NOTIFY\x10\x8b'\x12\x1e\n" +
	"\x19MESSAGE_ID_GM_COMMAND_REQ\x10\xf1.\x12\x1f\n" +
	"\x1aMESSAGE_ID_GM_COMMAND_RESP\x10\xf2.\x12\x15\n" +
	"\x10MESSAGE_ID_ERROR\x10\x8fN*f\n" +
	"\rBattleOutcome\x12\x1e\n" +
	"\x1aBATTLE_OUTCOME_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16BATTLE_OUTCOME_VICTORY\x10\x01\x12\x19\n" +
	"\x15BATTLE_OUTCOME_DEFEAT\x10\x02B<Z*game-server/internal/protocolpb;protocolpb\xaa\x02\rGame.Protocolb\x06proto3"

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData []byte
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)))
	})
	return file_game_proto_rawDescData
}

var file_game_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_game_proto_goTypes = []any{
	(MessageId)(0),                // 0: game.protocol.v1.MessageId
	(BattleOutcome)(0),            // 1: game.protocol.v1.BattleOutcome
	(*LoginReq)(nil),              // 2: game.protocol.v1.LoginReq
	(*LoginResp)(nil),             // 3: game.protocol.v1.LoginResp
	(*HeartbeatReq)(nil),          // 4: game.protocol.v1.HeartbeatReq
	(*HeartbeatResp)(nil),         // 5: game.protocol.v1.HeartbeatResp
	(*PlayerArchive)(nil),         // 6: game.protocol.v1.PlayerArchive
	(*SaveArchiveReq)(nil),        // 7: game.protocol.v1.SaveArchiveReq
	(*SaveArchiveResp)(nil),       // 8: game.protocol.v1.SaveArchiveResp
	(*LoadArchiveReq)(nil),        // 9: game.protocol.v1.LoadArchiveReq
	(*LoadArchiveResp)(nil),       // 10: game.protocol.v1.LoadArchiveResp
	(*GetRankReq)(nil),            // 11: game.protocol.v1.GetRankReq
	(*RankItem)(nil),              // 12: game.protocol.v1.RankItem
	(*GetRankResp)(nil),           // 13: game.protocol.v1.GetRankResp
	(*ScoreMetadata)(nil),         // 14: game.protocol.v1.ScoreMetadata
	(*SubmitScoreReq)(nil),        // 15: game.protocol.v1.SubmitScoreReq
	(*SubmitScoreResp)(nil),       // 16: game.protocol.v1.SubmitScoreResp
	(*CombatResultReq)(nil),       // 17: game.protocol.v1.CombatResultReq
	(*CombatResultResp)(nil),      // 18: game.protocol.v1.CombatResultResp
	(*EnemyConfigItem)(nil),       // 19: game.protocol.v1.EnemyConfigItem
	(*GetEnemyConfigsReq)(nil),    // 20: game.protocol.v1.GetEnemyConfigsReq
	(*GetEnemyConfigsResp)(nil),   // 21: game.protocol.v1.GetEnemyConfigsResp
	(*DungeonConfigItem)(nil),     // 22: game.protocol.v1.DungeonConfigItem
	(*GetDungeonConfigReq)(nil),   // 23: game.protocol.v1.GetDungeonConfigReq
	(*GetDungeonConfigResp)(nil),  // 24: game.protocol.v1.GetDungeonConfigResp
	(*StyleConfigItem)(nil),       // 25: game.protocol.v1.StyleConfigItem
	(*GetStyleConfigsReq)(nil),    // 26: game.protocol.v1.GetStyleConfigsReq
	(*GetStyleConfigsResp)(nil),   // 27: game.protocol.v1.GetStyleConfigsResp
	(*UnlockStyleReq)(nil),        // 28: game.protocol.v1.UnlockStyleReq
	(*UnlockStyleResp)(nil),       // 29: game.protocol.v1.UnlockStyleResp
	(*PlayerStatsData)(nil),       // 30: game.protocol.v1.PlayerStatsData
	(*GetPlayerStatsReq)(nil),     // 31: game.protocol.v1.GetPlayerStatsReq
	(*GetPlayerStatsResp)(nil),    // 32: game.protocol.v1.GetPlayerStatsResp
	(*UpdatePlayerStatsReq)(nil),  // 33: game.protocol.v1.UpdatePlayerStatsReq
	(*UpdatePlayerStatsResp)(nil), // 34: game.protocol.v1.UpdatePlayerStatsResp
	(*CreateOrderReq)(nil),        // 35: game.protocol.v1.CreateOrderReq
	(*CreateOrderResp)(nil),       // 36: game.protocol.v1.CreateOrderResp
	(*PayResultNotify)(nil),       // 37: game.protocol.v1.PayResultNotify
	(*GMCommandReq)(nil),          // 38: game.protocol.v1.GMCommandReq
	(*GMCommandResp)(nil),         // 39: game.protocol.v1.GMCommandResp
	(*ErrorResp)(nil),             // 40: game.protocol.v1.ErrorResp
}
var file_game_proto_depIdxs = []int32{
	6,  // 0: game.protocol.v1.SaveArchiveReq.archive:type_name -> game.protocol.v1.PlayerArchive
	6,  // 1: game.protocol.v1.LoadArchiveResp.archive:type_name -> game.protocol.v1.PlayerArchive
	12, // 2: game.protocol.v1.GetRankResp.ranks:type_name -> game.protocol.v1.RankItem
	14, // 3: game.protocol.v1.SubmitScoreReq.metadata:type_name -> game.protocol.v1.ScoreMetadata
	1,  // 4: game.protocol.v1.CombatResultReq.outcome:type_name -> game.protocol.v1.BattleOutcome
	6,  // 5: game.protocol.v1.CombatResultResp.archive:type_name -> game.protocol.v1.PlayerArchive
	19, // 6: game.protocol.v1.GetEnemyConfigsResp.configs:type_name -> game.protocol.v1.EnemyConfigItem
	19, // 7: game.protocol.v1.GetDungeonConfigResp.enemy_configs:type_name -> game.protocol.v1.EnemyConfigItem
	25, // 8: game.protocol.v1.GetStyleConfigsResp.styles:type_name -> game.protocol.v1.StyleConfigItem
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		EnumInfos:         file_game_proto_enumTypes,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
